version: "3"
services:
  netbird-dashboard:
    container_name: netbird-dashboard
    image: netbirdio/dashboard:latest
    restart: unless-stopped
    networks:
      - devops-lab_docker_network
    environment:
      # Endpoints
      - NETBIRD_MGMT_API_ENDPOINT=https://netbird.devopslab.in:443
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://netbird.devopslab.in:443
      # OIDC
      - AUTH_AUDIENCE=netbird-client
      - AUTH_CLIENT_ID=netbird-client
      - AUTH_CLIENT_SECRET=
      - AUTH_AUTHORITY=https://keycloak.devopslab.in/realms/devops-lab
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email offline_access netbird-api
      - AUTH_REDIRECT_URI=
      - AUTH_SILENT_REDIRECT_URI=
      - NETBIRD_TOKEN_SOURCE=accessToken
      # SSL
      - NGINX_SSL_PORT=443
      # Letsencrypt
      - LETSENCRYPT_DOMAIN=
      - LETSENCRYPT_EMAIL=

  # Signal
  netbird-signal:
    container_name: netbird-signal
    image: netbirdio/signal:latest
    restart: unless-stopped
    networks:
      - devops-lab_docker_network
    volumes:
      - /root/docker-storage/netbird-signal:/var/lib/netbird

  # Relay
  netbird-relay:
    container_name: netbird-relay
    image: netbirdio/relay:latest
    restart: unless-stopped
    networks:
      - devops-lab_docker_network
    environment:
    - NB_LOG_LEVEL=info
    - NB_LISTEN_ADDRESS=:33080
    - NB_EXPOSED_ADDRESS=netbird.devopslab.in:33080
    # todo: change to a secure secret
    - NB_AUTH_SECRET=fzH+unHHyipWVCEq/o1rfhbeYA+f7N0WTG/jPfbNQKw
    ports:
      - 33080:33080

  # Management
  netbird-management:
    container_name: netbird-management
    image: netbirdio/management:latest
    restart: unless-stopped
    networks:
      - devops-lab_docker_network
    depends_on:
      - netbird-dashboard
    volumes:
      - /root/docker-storage/netbird-mgmt:/var/lib/netbird
      - /root/docker-static/netbird-mgmt/management.json:/etc/netbird/management.json
    command: [
      "--port", "443",
      "--log-file", "console",
      "--log-level", "info",
      "--disable-anonymous-metrics=false",
      "--single-account-mode-domain=netbird.devopslab.in",
      "--dns-domain=in.devopslab.in"
      ]
    environment:
      - NETBIRD_STORE_ENGINE_POSTGRES_DSN=
      - NETBIRD_STORE_ENGINE_MYSQL_DSN=

  # Coturn
  netbird-coturn:
    container_name: netbird-coturn
    image: coturn/coturn:latest
    restart: unless-stopped
    domainname: netbird.devopslab.in
    volumes:
      - /root/docker-static/netbird-coturn/turnserver.conf:/etc/turnserver.conf:ro
    network_mode: host
    command:
      - -c /etc/turnserver.conf

networks:
  devops-lab_docker_network:
    external: true