http:
  routers:
    guacamole:
      rule: Host(`guacamole.{{env "HOST_DOMAIN"}}`)
      entryPoints:
        - web
      middlewares:
        - "force_https"
        - "error_pages"
      service: guacamole-service

    guacamole-ssl:
      rule: Host(`guacamole.{{env "HOST_DOMAIN"}}`)
      service: guacamole-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-default-resolver
      # middlewares:
      #   - "error_pages"
      #   - "internal_only"

  services:
    guacamole-service:
      loadBalancer:
        servers:
          - url: "http://10.20.0.211:8082"