global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'upstream-prometheus'

scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s  # Adjust as needed
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__=~".+"}'
    file_sd_configs:
      - files:
          - '/dynamic/prometheus.json'