---
title: DevOpsLab
headerStyle: boxed

background:
  image: https://images.unsplash.com/photo-1629056948919-2ff26272117e
  blur: xl
  brightness: 90
  opacity: 60

cardBlur: sm

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Networking:
    icon: mdi-network-#FFFFFF
  Network Services:
    icon: mdi-web-#FFFFFF
  Overlay and Proxy:
    icon: mdi-arrow-decision-#FFFFFF
  Infrastructure and Storage:
    icon: mdi-server-#FFFFFF
  Security and Identity:
    icon: mdi-shield-lock-#FFFFFF
  Management:
    icon: mdi-auto-fix-#FFFFFF
  Monitoring:
    icon: mdi-list-status-#FFFFFF
  Automation:
    icon: mdi-cog-play-#FFFFFF