http:
  routers:
    speedtest-tracker-site:
      rule: Host(`speed-site.{{env "HOST_DOMAIN"}}`)
      entryPoints:
        - web
      middlewares:
        - "force_https"
        - "error_pages"
      service: speedtest-tracker-site-service

    speedtest-tracker-site-ssl:
      rule: Host(`speed-site.{{env "HOST_DOMAIN"}}`)
      service: speedtest-tracker-site-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-default-resolver
      middlewares:
        - "error_pages"
        # - "internal_only"

  services:
    speedtest-tracker-site-service:
      loadBalancer:
        servers:
          - url: "http://172.25.1.2:8888"