version: '3'

services:
  prometheus-downstream:
    image: prom/prometheus:latest
    container_name: prometheus-downstream
    restart: always
    volumes:
      - /root/docker-static/prometheus-downstream/:/etc/prometheus/
      - /root/docker-storage/prometheus-downstream/dynamic:/dynamic
      - /root/docker-storage/prometheus-downstream/data:/prometheus
    networks:
      - devops-lab_docker_network
    ports:
      - "${HOST_LOCAL_IP}:9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - devops-lab_docker_network
    ports:
      - "${HOST_LOCAL_IP}:9100:9100"

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   restart: always
  #   ports:
  #     - "${HOST_LOCAL_IP}:8080:8080"
  #   networks:
  #     - devops-lab_docker_network
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker:/var/lib/docker:ro
  #     - /etc/machine-id:/etc/machine-id:ro
  #     - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
  #     - /dev/kmsg:/dev/kmsg:rw
  #   command: ["start", "--privileged"]

  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    restart: always
    networks:
      - devops-lab_docker_network
    ports:
      - "${HOST_LOCAL_IP}:8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      # - /etc/machine-id:/etc/machine-id:ro
      # - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
      # - /dev/kmsg:/dev/kmsg:rw
    #command: ["start", "--privileged"]

networks:
  devops-lab_docker_network:
    external: true