global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
      monitor: 'prometheus-grafana-exporter'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    file_sd_configs:
    - files:
      - '/dynamic/node.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance

  - job_name: 'cadvisor'
    scrape_interval: 5s
    file_sd_configs:
    - files:
      - '/dynamic/cadvisor.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance


